/**
 * Autogenerated by Avro
 * 
 * DO NOT EDIT DIRECTLY
 */
package com.aqitrade.raduga.messagebus.messages;  
@SuppressWarnings("all")
@org.apache.avro.specific.AvroGenerated
public enum AppMarginCommissionQueryStatus { 
  app_margin_commission_query_status_ok, app_margin_commission_query_status_failure  ;
  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"enum\",\"name\":\"AppMarginCommissionQueryStatus\",\"namespace\":\"com.aqitrade.raduga.messagebus.messages\",\"symbols\":[\"app_margin_commission_query_status_ok\",\"app_margin_commission_query_status_failure\"]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }
}
