/**
 * Autogenerated by Avro
 * 
 * DO NOT EDIT DIRECTLY
 */
package com.aqitrade.raduga.messagebus.messages;  
@SuppressWarnings("all")
@org.apache.avro.specific.AvroGenerated
public class BankFutureTransferStatusMessage extends org.apache.avro.specific.SpecificRecordBase implements org.apache.avro.specific.SpecificRecord {
  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"record\",\"name\":\"BankFutureTransferStatusMessage\",\"namespace\":\"com.aqitrade.raduga.messagebus.messages\",\"fields\":[{\"name\":\"transferId\",\"type\":\"long\"},{\"name\":\"brokerId\",\"type\":{\"type\":\"string\",\"avro.java.string\":\"String\"}},{\"name\":\"accountID\",\"type\":\"long\"},{\"name\":\"accountAuthId\",\"type\":{\"type\":\"string\",\"avro.java.string\":\"String\"}},{\"name\":\"tradeCode\",\"type\":{\"type\":\"string\",\"avro.java.string\":\"String\"}},{\"name\":\"bankID\",\"type\":{\"type\":\"string\",\"avro.java.string\":\"String\"}},{\"name\":\"bankBranchID\",\"type\":{\"type\":\"string\",\"avro.java.string\":\"String\"}},{\"name\":\"bankPassword\",\"type\":{\"type\":\"string\",\"avro.java.string\":\"String\"}},{\"name\":\"secuPwdFlag\",\"type\":{\"type\":\"string\",\"avro.java.string\":\"String\"}},{\"name\":\"currencyID\",\"type\":{\"type\":\"string\",\"avro.java.string\":\"String\"}},{\"name\":\"tradeAmount\",\"type\":\"double\"},{\"name\":\"errorMsg\",\"type\":{\"type\":\"string\",\"avro.java.string\":\"String\"}},{\"name\":\"createDate\",\"type\":{\"type\":\"string\",\"avro.java.string\":\"String\"}},{\"name\":\"errorID\",\"type\":\"long\"}]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }
  @Deprecated public long transferId;
  @Deprecated public String brokerId;
  @Deprecated public long accountID;
  @Deprecated public String accountAuthId;
  @Deprecated public String tradeCode;
  @Deprecated public String bankID;
  @Deprecated public String bankBranchID;
  @Deprecated public String bankPassword;
  @Deprecated public String secuPwdFlag;
  @Deprecated public String currencyID;
  @Deprecated public double tradeAmount;
  @Deprecated public String errorMsg;
  @Deprecated public String createDate;
  @Deprecated public long errorID;

  /**
   * Default constructor.  Note that this does not initialize fields
   * to their default values from the schema.  If that is desired then
   * one should use {@link \#newBuilder()}. 
   */
  public BankFutureTransferStatusMessage() {}

  /**
   * All-args constructor.
   */
  public BankFutureTransferStatusMessage(Long transferId, String brokerId, Long accountID, String accountAuthId, String tradeCode, String bankID, String bankBranchID, String bankPassword, String secuPwdFlag, String currencyID, Double tradeAmount, String errorMsg, String createDate, Long errorID) {
    this.transferId = transferId;
    this.brokerId = brokerId;
    this.accountID = accountID;
    this.accountAuthId = accountAuthId;
    this.tradeCode = tradeCode;
    this.bankID = bankID;
    this.bankBranchID = bankBranchID;
    this.bankPassword = bankPassword;
    this.secuPwdFlag = secuPwdFlag;
    this.currencyID = currencyID;
    this.tradeAmount = tradeAmount;
    this.errorMsg = errorMsg;
    this.createDate = createDate;
    this.errorID = errorID;
  }

  public org.apache.avro.Schema getSchema() { return SCHEMA$; }
  // Used by DatumWriter.  Applications should not call. 
  public Object get(int field$) {
    switch (field$) {
    case 0: return transferId;
    case 1: return brokerId;
    case 2: return accountID;
    case 3: return accountAuthId;
    case 4: return tradeCode;
    case 5: return bankID;
    case 6: return bankBranchID;
    case 7: return bankPassword;
    case 8: return secuPwdFlag;
    case 9: return currencyID;
    case 10: return tradeAmount;
    case 11: return errorMsg;
    case 12: return createDate;
    case 13: return errorID;
    default: throw new org.apache.avro.AvroRuntimeException("Bad index");
    }
  }
  // Used by DatumReader.  Applications should not call. 
  @SuppressWarnings(value="unchecked")
  public void put(int field$, Object value$) {
    switch (field$) {
    case 0: transferId = (Long)value$; break;
    case 1: brokerId = (String)value$; break;
    case 2: accountID = (Long)value$; break;
    case 3: accountAuthId = (String)value$; break;
    case 4: tradeCode = (String)value$; break;
    case 5: bankID = (String)value$; break;
    case 6: bankBranchID = (String)value$; break;
    case 7: bankPassword = (String)value$; break;
    case 8: secuPwdFlag = (String)value$; break;
    case 9: currencyID = (String)value$; break;
    case 10: tradeAmount = (Double)value$; break;
    case 11: errorMsg = (String)value$; break;
    case 12: createDate = (String)value$; break;
    case 13: errorID = (Long)value$; break;
    default: throw new org.apache.avro.AvroRuntimeException("Bad index");
    }
  }

  /**
   * Gets the value of the 'transferId' field.
   */
  public Long getTransferId() {
    return transferId;
  }

  /**
   * Sets the value of the 'transferId' field.
   * @param value the value to set.
   */
  public void setTransferId(Long value) {
    this.transferId = value;
  }

  /**
   * Gets the value of the 'brokerId' field.
   */
  public String getBrokerId() {
    return brokerId;
  }

  /**
   * Sets the value of the 'brokerId' field.
   * @param value the value to set.
   */
  public void setBrokerId(String value) {
    this.brokerId = value;
  }

  /**
   * Gets the value of the 'accountID' field.
   */
  public Long getAccountID() {
    return accountID;
  }

  /**
   * Sets the value of the 'accountID' field.
   * @param value the value to set.
   */
  public void setAccountID(Long value) {
    this.accountID = value;
  }

  /**
   * Gets the value of the 'accountAuthId' field.
   */
  public String getAccountAuthId() {
    return accountAuthId;
  }

  /**
   * Sets the value of the 'accountAuthId' field.
   * @param value the value to set.
   */
  public void setAccountAuthId(String value) {
    this.accountAuthId = value;
  }

  /**
   * Gets the value of the 'tradeCode' field.
   */
  public String getTradeCode() {
    return tradeCode;
  }

  /**
   * Sets the value of the 'tradeCode' field.
   * @param value the value to set.
   */
  public void setTradeCode(String value) {
    this.tradeCode = value;
  }

  /**
   * Gets the value of the 'bankID' field.
   */
  public String getBankID() {
    return bankID;
  }

  /**
   * Sets the value of the 'bankID' field.
   * @param value the value to set.
   */
  public void setBankID(String value) {
    this.bankID = value;
  }

  /**
   * Gets the value of the 'bankBranchID' field.
   */
  public String getBankBranchID() {
    return bankBranchID;
  }

  /**
   * Sets the value of the 'bankBranchID' field.
   * @param value the value to set.
   */
  public void setBankBranchID(String value) {
    this.bankBranchID = value;
  }

  /**
   * Gets the value of the 'bankPassword' field.
   */
  public String getBankPassword() {
    return bankPassword;
  }

  /**
   * Sets the value of the 'bankPassword' field.
   * @param value the value to set.
   */
  public void setBankPassword(String value) {
    this.bankPassword = value;
  }

  /**
   * Gets the value of the 'secuPwdFlag' field.
   */
  public String getSecuPwdFlag() {
    return secuPwdFlag;
  }

  /**
   * Sets the value of the 'secuPwdFlag' field.
   * @param value the value to set.
   */
  public void setSecuPwdFlag(String value) {
    this.secuPwdFlag = value;
  }

  /**
   * Gets the value of the 'currencyID' field.
   */
  public String getCurrencyID() {
    return currencyID;
  }

  /**
   * Sets the value of the 'currencyID' field.
   * @param value the value to set.
   */
  public void setCurrencyID(String value) {
    this.currencyID = value;
  }

  /**
   * Gets the value of the 'tradeAmount' field.
   */
  public Double getTradeAmount() {
    return tradeAmount;
  }

  /**
   * Sets the value of the 'tradeAmount' field.
   * @param value the value to set.
   */
  public void setTradeAmount(Double value) {
    this.tradeAmount = value;
  }

  /**
   * Gets the value of the 'errorMsg' field.
   */
  public String getErrorMsg() {
    return errorMsg;
  }

  /**
   * Sets the value of the 'errorMsg' field.
   * @param value the value to set.
   */
  public void setErrorMsg(String value) {
    this.errorMsg = value;
  }

  /**
   * Gets the value of the 'createDate' field.
   */
  public String getCreateDate() {
    return createDate;
  }

  /**
   * Sets the value of the 'createDate' field.
   * @param value the value to set.
   */
  public void setCreateDate(String value) {
    this.createDate = value;
  }

  /**
   * Gets the value of the 'errorID' field.
   */
  public Long getErrorID() {
    return errorID;
  }

  /**
   * Sets the value of the 'errorID' field.
   * @param value the value to set.
   */
  public void setErrorID(Long value) {
    this.errorID = value;
  }

  /** Creates a new BankFutureTransferStatusMessage RecordBuilder */
  public static Builder newBuilder() {
    return new Builder();
  }
  
  /** Creates a new BankFutureTransferStatusMessage RecordBuilder by copying an existing Builder */
  public static Builder newBuilder(Builder other) {
    return new Builder(other);
  }
  
  /** Creates a new BankFutureTransferStatusMessage RecordBuilder by copying an existing BankFutureTransferStatusMessage instance */
  public static Builder newBuilder(BankFutureTransferStatusMessage other) {
    return new Builder(other);
  }
  
  /**
   * RecordBuilder for BankFutureTransferStatusMessage instances.
   */
  public static class Builder extends org.apache.avro.specific.SpecificRecordBuilderBase<BankFutureTransferStatusMessage>
    implements org.apache.avro.data.RecordBuilder<BankFutureTransferStatusMessage> {

    private long transferId;
    private String brokerId;
    private long accountID;
    private String accountAuthId;
    private String tradeCode;
    private String bankID;
    private String bankBranchID;
    private String bankPassword;
    private String secuPwdFlag;
    private String currencyID;
    private double tradeAmount;
    private String errorMsg;
    private String createDate;
    private long errorID;

    /** Creates a new Builder */
    private Builder() {
      super(BankFutureTransferStatusMessage.SCHEMA$);
    }
    
    /** Creates a Builder by copying an existing Builder */
    private Builder(Builder other) {
      super(other);
      if (isValidValue(fields()[0], other.transferId)) {
        this.transferId = data().deepCopy(fields()[0].schema(), other.transferId);
        fieldSetFlags()[0] = true;
      }
      if (isValidValue(fields()[1], other.brokerId)) {
        this.brokerId = data().deepCopy(fields()[1].schema(), other.brokerId);
        fieldSetFlags()[1] = true;
      }
      if (isValidValue(fields()[2], other.accountID)) {
        this.accountID = data().deepCopy(fields()[2].schema(), other.accountID);
        fieldSetFlags()[2] = true;
      }
      if (isValidValue(fields()[3], other.accountAuthId)) {
        this.accountAuthId = data().deepCopy(fields()[3].schema(), other.accountAuthId);
        fieldSetFlags()[3] = true;
      }
      if (isValidValue(fields()[4], other.tradeCode)) {
        this.tradeCode = data().deepCopy(fields()[4].schema(), other.tradeCode);
        fieldSetFlags()[4] = true;
      }
      if (isValidValue(fields()[5], other.bankID)) {
        this.bankID = data().deepCopy(fields()[5].schema(), other.bankID);
        fieldSetFlags()[5] = true;
      }
      if (isValidValue(fields()[6], other.bankBranchID)) {
        this.bankBranchID = data().deepCopy(fields()[6].schema(), other.bankBranchID);
        fieldSetFlags()[6] = true;
      }
      if (isValidValue(fields()[7], other.bankPassword)) {
        this.bankPassword = data().deepCopy(fields()[7].schema(), other.bankPassword);
        fieldSetFlags()[7] = true;
      }
      if (isValidValue(fields()[8], other.secuPwdFlag)) {
        this.secuPwdFlag = data().deepCopy(fields()[8].schema(), other.secuPwdFlag);
        fieldSetFlags()[8] = true;
      }
      if (isValidValue(fields()[9], other.currencyID)) {
        this.currencyID = data().deepCopy(fields()[9].schema(), other.currencyID);
        fieldSetFlags()[9] = true;
      }
      if (isValidValue(fields()[10], other.tradeAmount)) {
        this.tradeAmount = data().deepCopy(fields()[10].schema(), other.tradeAmount);
        fieldSetFlags()[10] = true;
      }
      if (isValidValue(fields()[11], other.errorMsg)) {
        this.errorMsg = data().deepCopy(fields()[11].schema(), other.errorMsg);
        fieldSetFlags()[11] = true;
      }
      if (isValidValue(fields()[12], other.createDate)) {
        this.createDate = data().deepCopy(fields()[12].schema(), other.createDate);
        fieldSetFlags()[12] = true;
      }
      if (isValidValue(fields()[13], other.errorID)) {
        this.errorID = data().deepCopy(fields()[13].schema(), other.errorID);
        fieldSetFlags()[13] = true;
      }
    }
    
    /** Creates a Builder by copying an existing BankFutureTransferStatusMessage instance */
    private Builder(BankFutureTransferStatusMessage other) {
            super(BankFutureTransferStatusMessage.SCHEMA$);
      if (isValidValue(fields()[0], other.transferId)) {
        this.transferId = data().deepCopy(fields()[0].schema(), other.transferId);
        fieldSetFlags()[0] = true;
      }
      if (isValidValue(fields()[1], other.brokerId)) {
        this.brokerId = data().deepCopy(fields()[1].schema(), other.brokerId);
        fieldSetFlags()[1] = true;
      }
      if (isValidValue(fields()[2], other.accountID)) {
        this.accountID = data().deepCopy(fields()[2].schema(), other.accountID);
        fieldSetFlags()[2] = true;
      }
      if (isValidValue(fields()[3], other.accountAuthId)) {
        this.accountAuthId = data().deepCopy(fields()[3].schema(), other.accountAuthId);
        fieldSetFlags()[3] = true;
      }
      if (isValidValue(fields()[4], other.tradeCode)) {
        this.tradeCode = data().deepCopy(fields()[4].schema(), other.tradeCode);
        fieldSetFlags()[4] = true;
      }
      if (isValidValue(fields()[5], other.bankID)) {
        this.bankID = data().deepCopy(fields()[5].schema(), other.bankID);
        fieldSetFlags()[5] = true;
      }
      if (isValidValue(fields()[6], other.bankBranchID)) {
        this.bankBranchID = data().deepCopy(fields()[6].schema(), other.bankBranchID);
        fieldSetFlags()[6] = true;
      }
      if (isValidValue(fields()[7], other.bankPassword)) {
        this.bankPassword = data().deepCopy(fields()[7].schema(), other.bankPassword);
        fieldSetFlags()[7] = true;
      }
      if (isValidValue(fields()[8], other.secuPwdFlag)) {
        this.secuPwdFlag = data().deepCopy(fields()[8].schema(), other.secuPwdFlag);
        fieldSetFlags()[8] = true;
      }
      if (isValidValue(fields()[9], other.currencyID)) {
        this.currencyID = data().deepCopy(fields()[9].schema(), other.currencyID);
        fieldSetFlags()[9] = true;
      }
      if (isValidValue(fields()[10], other.tradeAmount)) {
        this.tradeAmount = data().deepCopy(fields()[10].schema(), other.tradeAmount);
        fieldSetFlags()[10] = true;
      }
      if (isValidValue(fields()[11], other.errorMsg)) {
        this.errorMsg = data().deepCopy(fields()[11].schema(), other.errorMsg);
        fieldSetFlags()[11] = true;
      }
      if (isValidValue(fields()[12], other.createDate)) {
        this.createDate = data().deepCopy(fields()[12].schema(), other.createDate);
        fieldSetFlags()[12] = true;
      }
      if (isValidValue(fields()[13], other.errorID)) {
        this.errorID = data().deepCopy(fields()[13].schema(), other.errorID);
        fieldSetFlags()[13] = true;
      }
    }

    /** Gets the value of the 'transferId' field */
    public Long getTransferId() {
      return transferId;
    }
    
    /** Sets the value of the 'transferId' field */
    public Builder setTransferId(long value) {
      validate(fields()[0], value);
      this.transferId = value;
      fieldSetFlags()[0] = true;
      return this; 
    }
    
    /** Checks whether the 'transferId' field has been set */
    public boolean hasTransferId() {
      return fieldSetFlags()[0];
    }
    
    /** Clears the value of the 'transferId' field */
    public Builder clearTransferId() {
      fieldSetFlags()[0] = false;
      return this;
    }

    /** Gets the value of the 'brokerId' field */
    public String getBrokerId() {
      return brokerId;
    }
    
    /** Sets the value of the 'brokerId' field */
    public Builder setBrokerId(String value) {
      validate(fields()[1], value);
      this.brokerId = value;
      fieldSetFlags()[1] = true;
      return this; 
    }
    
    /** Checks whether the 'brokerId' field has been set */
    public boolean hasBrokerId() {
      return fieldSetFlags()[1];
    }
    
    /** Clears the value of the 'brokerId' field */
    public Builder clearBrokerId() {
      brokerId = null;
      fieldSetFlags()[1] = false;
      return this;
    }

    /** Gets the value of the 'accountID' field */
    public Long getAccountID() {
      return accountID;
    }
    
    /** Sets the value of the 'accountID' field */
    public Builder setAccountID(long value) {
      validate(fields()[2], value);
      this.accountID = value;
      fieldSetFlags()[2] = true;
      return this; 
    }
    
    /** Checks whether the 'accountID' field has been set */
    public boolean hasAccountID() {
      return fieldSetFlags()[2];
    }
    
    /** Clears the value of the 'accountID' field */
    public Builder clearAccountID() {
      fieldSetFlags()[2] = false;
      return this;
    }

    /** Gets the value of the 'accountAuthId' field */
    public String getAccountAuthId() {
      return accountAuthId;
    }
    
    /** Sets the value of the 'accountAuthId' field */
    public Builder setAccountAuthId(String value) {
      validate(fields()[3], value);
      this.accountAuthId = value;
      fieldSetFlags()[3] = true;
      return this; 
    }
    
    /** Checks whether the 'accountAuthId' field has been set */
    public boolean hasAccountAuthId() {
      return fieldSetFlags()[3];
    }
    
    /** Clears the value of the 'accountAuthId' field */
    public Builder clearAccountAuthId() {
      accountAuthId = null;
      fieldSetFlags()[3] = false;
      return this;
    }

    /** Gets the value of the 'tradeCode' field */
    public String getTradeCode() {
      return tradeCode;
    }
    
    /** Sets the value of the 'tradeCode' field */
    public Builder setTradeCode(String value) {
      validate(fields()[4], value);
      this.tradeCode = value;
      fieldSetFlags()[4] = true;
      return this; 
    }
    
    /** Checks whether the 'tradeCode' field has been set */
    public boolean hasTradeCode() {
      return fieldSetFlags()[4];
    }
    
    /** Clears the value of the 'tradeCode' field */
    public Builder clearTradeCode() {
      tradeCode = null;
      fieldSetFlags()[4] = false;
      return this;
    }

    /** Gets the value of the 'bankID' field */
    public String getBankID() {
      return bankID;
    }
    
    /** Sets the value of the 'bankID' field */
    public Builder setBankID(String value) {
      validate(fields()[5], value);
      this.bankID = value;
      fieldSetFlags()[5] = true;
      return this; 
    }
    
    /** Checks whether the 'bankID' field has been set */
    public boolean hasBankID() {
      return fieldSetFlags()[5];
    }
    
    /** Clears the value of the 'bankID' field */
    public Builder clearBankID() {
      bankID = null;
      fieldSetFlags()[5] = false;
      return this;
    }

    /** Gets the value of the 'bankBranchID' field */
    public String getBankBranchID() {
      return bankBranchID;
    }
    
    /** Sets the value of the 'bankBranchID' field */
    public Builder setBankBranchID(String value) {
      validate(fields()[6], value);
      this.bankBranchID = value;
      fieldSetFlags()[6] = true;
      return this; 
    }
    
    /** Checks whether the 'bankBranchID' field has been set */
    public boolean hasBankBranchID() {
      return fieldSetFlags()[6];
    }
    
    /** Clears the value of the 'bankBranchID' field */
    public Builder clearBankBranchID() {
      bankBranchID = null;
      fieldSetFlags()[6] = false;
      return this;
    }

    /** Gets the value of the 'bankPassword' field */
    public String getBankPassword() {
      return bankPassword;
    }
    
    /** Sets the value of the 'bankPassword' field */
    public Builder setBankPassword(String value) {
      validate(fields()[7], value);
      this.bankPassword = value;
      fieldSetFlags()[7] = true;
      return this; 
    }
    
    /** Checks whether the 'bankPassword' field has been set */
    public boolean hasBankPassword() {
      return fieldSetFlags()[7];
    }
    
    /** Clears the value of the 'bankPassword' field */
    public Builder clearBankPassword() {
      bankPassword = null;
      fieldSetFlags()[7] = false;
      return this;
    }

    /** Gets the value of the 'secuPwdFlag' field */
    public String getSecuPwdFlag() {
      return secuPwdFlag;
    }
    
    /** Sets the value of the 'secuPwdFlag' field */
    public Builder setSecuPwdFlag(String value) {
      validate(fields()[8], value);
      this.secuPwdFlag = value;
      fieldSetFlags()[8] = true;
      return this; 
    }
    
    /** Checks whether the 'secuPwdFlag' field has been set */
    public boolean hasSecuPwdFlag() {
      return fieldSetFlags()[8];
    }
    
    /** Clears the value of the 'secuPwdFlag' field */
    public Builder clearSecuPwdFlag() {
      secuPwdFlag = null;
      fieldSetFlags()[8] = false;
      return this;
    }

    /** Gets the value of the 'currencyID' field */
    public String getCurrencyID() {
      return currencyID;
    }
    
    /** Sets the value of the 'currencyID' field */
    public Builder setCurrencyID(String value) {
      validate(fields()[9], value);
      this.currencyID = value;
      fieldSetFlags()[9] = true;
      return this; 
    }
    
    /** Checks whether the 'currencyID' field has been set */
    public boolean hasCurrencyID() {
      return fieldSetFlags()[9];
    }
    
    /** Clears the value of the 'currencyID' field */
    public Builder clearCurrencyID() {
      currencyID = null;
      fieldSetFlags()[9] = false;
      return this;
    }

    /** Gets the value of the 'tradeAmount' field */
    public Double getTradeAmount() {
      return tradeAmount;
    }
    
    /** Sets the value of the 'tradeAmount' field */
    public Builder setTradeAmount(double value) {
      validate(fields()[10], value);
      this.tradeAmount = value;
      fieldSetFlags()[10] = true;
      return this; 
    }
    
    /** Checks whether the 'tradeAmount' field has been set */
    public boolean hasTradeAmount() {
      return fieldSetFlags()[10];
    }
    
    /** Clears the value of the 'tradeAmount' field */
    public Builder clearTradeAmount() {
      fieldSetFlags()[10] = false;
      return this;
    }

    /** Gets the value of the 'errorMsg' field */
    public String getErrorMsg() {
      return errorMsg;
    }
    
    /** Sets the value of the 'errorMsg' field */
    public Builder setErrorMsg(String value) {
      validate(fields()[11], value);
      this.errorMsg = value;
      fieldSetFlags()[11] = true;
      return this; 
    }
    
    /** Checks whether the 'errorMsg' field has been set */
    public boolean hasErrorMsg() {
      return fieldSetFlags()[11];
    }
    
    /** Clears the value of the 'errorMsg' field */
    public Builder clearErrorMsg() {
      errorMsg = null;
      fieldSetFlags()[11] = false;
      return this;
    }

    /** Gets the value of the 'createDate' field */
    public String getCreateDate() {
      return createDate;
    }
    
    /** Sets the value of the 'createDate' field */
    public Builder setCreateDate(String value) {
      validate(fields()[12], value);
      this.createDate = value;
      fieldSetFlags()[12] = true;
      return this; 
    }
    
    /** Checks whether the 'createDate' field has been set */
    public boolean hasCreateDate() {
      return fieldSetFlags()[12];
    }
    
    /** Clears the value of the 'createDate' field */
    public Builder clearCreateDate() {
      createDate = null;
      fieldSetFlags()[12] = false;
      return this;
    }

    /** Gets the value of the 'errorID' field */
    public Long getErrorID() {
      return errorID;
    }
    
    /** Sets the value of the 'errorID' field */
    public Builder setErrorID(long value) {
      validate(fields()[13], value);
      this.errorID = value;
      fieldSetFlags()[13] = true;
      return this; 
    }
    
    /** Checks whether the 'errorID' field has been set */
    public boolean hasErrorID() {
      return fieldSetFlags()[13];
    }
    
    /** Clears the value of the 'errorID' field */
    public Builder clearErrorID() {
      fieldSetFlags()[13] = false;
      return this;
    }

    @Override
    public BankFutureTransferStatusMessage build() {
      try {
        BankFutureTransferStatusMessage record = new BankFutureTransferStatusMessage();
        record.transferId = fieldSetFlags()[0] ? this.transferId : (Long) defaultValue(fields()[0]);
        record.brokerId = fieldSetFlags()[1] ? this.brokerId : (String) defaultValue(fields()[1]);
        record.accountID = fieldSetFlags()[2] ? this.accountID : (Long) defaultValue(fields()[2]);
        record.accountAuthId = fieldSetFlags()[3] ? this.accountAuthId : (String) defaultValue(fields()[3]);
        record.tradeCode = fieldSetFlags()[4] ? this.tradeCode : (String) defaultValue(fields()[4]);
        record.bankID = fieldSetFlags()[5] ? this.bankID : (String) defaultValue(fields()[5]);
        record.bankBranchID = fieldSetFlags()[6] ? this.bankBranchID : (String) defaultValue(fields()[6]);
        record.bankPassword = fieldSetFlags()[7] ? this.bankPassword : (String) defaultValue(fields()[7]);
        record.secuPwdFlag = fieldSetFlags()[8] ? this.secuPwdFlag : (String) defaultValue(fields()[8]);
        record.currencyID = fieldSetFlags()[9] ? this.currencyID : (String) defaultValue(fields()[9]);
        record.tradeAmount = fieldSetFlags()[10] ? this.tradeAmount : (Double) defaultValue(fields()[10]);
        record.errorMsg = fieldSetFlags()[11] ? this.errorMsg : (String) defaultValue(fields()[11]);
        record.createDate = fieldSetFlags()[12] ? this.createDate : (String) defaultValue(fields()[12]);
        record.errorID = fieldSetFlags()[13] ? this.errorID : (Long) defaultValue(fields()[13]);
        return record;
      } catch (Exception e) {
        throw new org.apache.avro.AvroRuntimeException(e);
      }
    }
  }
}
