/**
 * Autogenerated by Avro
 * 
 * DO NOT EDIT DIRECTLY
 */
package com.aqitrade.raduga.messagebus.messages;  
@SuppressWarnings("all")
@org.apache.avro.specific.AvroGenerated
public enum CommissionType { 
  commission_by_volume, commission_by_money  ;
  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"enum\",\"name\":\"CommissionType\",\"namespace\":\"com.aqitrade.raduga.messagebus.messages\",\"symbols\":[\"commission_by_volume\",\"commission_by_money\"]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }
}
