/**
 * Autogenerated by Avro
 * 
 * DO NOT EDIT DIRECTLY
 */
package com.aqitrade.raduga.messagebus.messages;  
@SuppressWarnings("all")
@org.apache.avro.specific.AvroGenerated
public enum ConnectionStatus { 
  connection_status_ok, connection_status_failure  ;
  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"enum\",\"name\":\"ConnectionStatus\",\"namespace\":\"com.aqitrade.raduga.messagebus.messages\",\"symbols\":[\"connection_status_ok\",\"connection_status_failure\"]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }
}
