/**
 * Autogenerated by Avro
 * 
 * DO NOT EDIT DIRECTLY
 */
package com.aqitrade.raduga.messagebus.messages;  
@SuppressWarnings("all")
@org.apache.avro.specific.AvroGenerated
public enum MarginType { 
  margin_by_volume, margin_by_money  ;
  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"enum\",\"name\":\"MarginType\",\"namespace\":\"com.aqitrade.raduga.messagebus.messages\",\"symbols\":[\"margin_by_volume\",\"margin_by_money\"]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }
}
