/**
 * Autogenerated by Avro
 * 
 * DO NOT EDIT DIRECTLY
 */
package com.aqitrade.raduga.messagebus.messages;  
@SuppressWarnings("all")
@org.apache.avro.specific.AvroGenerated
public class OrderStatusMessage extends org.apache.avro.specific.SpecificRecordBase implements org.apache.avro.specific.SpecificRecord {
  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"record\",\"name\":\"OrderStatusMessage\",\"namespace\":\"com.aqitrade.raduga.messagebus.messages\",\"fields\":[{\"name\":\"orderID\",\"type\":\"long\"},{\"name\":\"exchangeOrderID\",\"type\":{\"type\":\"string\",\"avro.java.string\":\"String\"}},{\"name\":\"qty\",\"type\":\"int\"},{\"name\":\"status\",\"type\":{\"type\":\"enum\",\"name\":\"OrderStatus\",\"symbols\":[\"order_status_new\",\"order_status_cancel_submitted\",\"order_status_executed\",\"order_status_rejected\",\"order_status_cancelled\",\"order_status_submitted\",\"order_status_part_executed\",\"order_status_no_cancel\",\"order_status_repeat_cancel\",\"order_status_undefined\"]}},{\"name\":\"statusMessage\",\"type\":{\"type\":\"string\",\"avro.java.string\":\"String\"}},{\"name\":\"createDate\",\"type\":{\"type\":\"string\",\"avro.java.string\":\"String\"}},{\"name\":\"insertTime\",\"type\":{\"type\":\"string\",\"avro.java.string\":\"String\"}},{\"name\":\"external\",\"type\":\"boolean\"},{\"name\":\"accountAuthId\",\"type\":{\"type\":\"string\",\"avro.java.string\":\"String\"}},{\"name\":\"symbol\",\"type\":{\"type\":\"string\",\"avro.java.string\":\"String\"}},{\"name\":\"direction\",\"type\":{\"type\":\"enum\",\"name\":\"OrderStatusDirection\",\"symbols\":[\"order_status_direction_long\",\"order_status_direction_short\"]}},{\"name\":\"price\",\"type\":\"double\"},{\"name\":\"submittedQty\",\"type\":\"int\"},{\"name\":\"closeToday\",\"type\":\"boolean\"},{\"name\":\"exchangeID\",\"type\":{\"type\":\"string\",\"avro.java.string\":\"String\"}}]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }
  @Deprecated public long orderID;
  @Deprecated public String exchangeOrderID;
  @Deprecated public int qty;
  @Deprecated public OrderStatus status;
  @Deprecated public String statusMessage;
  @Deprecated public String createDate;
  @Deprecated public String insertTime;
  @Deprecated public boolean external;
  @Deprecated public String accountAuthId;
  @Deprecated public String symbol;
  @Deprecated public com.aqitrade.raduga.messagebus.messages.OrderStatusDirection direction;
  @Deprecated public double price;
  @Deprecated public int submittedQty;
  @Deprecated public boolean closeToday;
  @Deprecated public String exchangeID;

  /**
   * Default constructor.  Note that this does not initialize fields
   * to their default values from the schema.  If that is desired then
   * one should use {@link \#newBuilder()}. 
   */
  public OrderStatusMessage() {}

  /**
   * All-args constructor.
   */
  public OrderStatusMessage(Long orderID, String exchangeOrderID, Integer qty, OrderStatus status, String statusMessage, String createDate, String insertTime, Boolean external, String accountAuthId, String symbol, com.aqitrade.raduga.messagebus.messages.OrderStatusDirection direction, Double price, Integer submittedQty, Boolean closeToday, String exchangeID) {
    this.orderID = orderID;
    this.exchangeOrderID = exchangeOrderID;
    this.qty = qty;
    this.status = status;
    this.statusMessage = statusMessage;
    this.createDate = createDate;
    this.insertTime = insertTime;
    this.external = external;
    this.accountAuthId = accountAuthId;
    this.symbol = symbol;
    this.direction = direction;
    this.price = price;
    this.submittedQty = submittedQty;
    this.closeToday = closeToday;
    this.exchangeID = exchangeID;
  }

  public org.apache.avro.Schema getSchema() { return SCHEMA$; }
  // Used by DatumWriter.  Applications should not call. 
  public Object get(int field$) {
    switch (field$) {
    case 0: return orderID;
    case 1: return exchangeOrderID;
    case 2: return qty;
    case 3: return status;
    case 4: return statusMessage;
    case 5: return createDate;
    case 6: return insertTime;
    case 7: return external;
    case 8: return accountAuthId;
    case 9: return symbol;
    case 10: return direction;
    case 11: return price;
    case 12: return submittedQty;
    case 13: return closeToday;
    case 14: return exchangeID;
    default: throw new org.apache.avro.AvroRuntimeException("Bad index");
    }
  }
  // Used by DatumReader.  Applications should not call. 
  @SuppressWarnings(value="unchecked")
  public void put(int field$, Object value$) {
    switch (field$) {
    case 0: orderID = (Long)value$; break;
    case 1: exchangeOrderID = (String)value$; break;
    case 2: qty = (Integer)value$; break;
    case 3: status = (OrderStatus)value$; break;
    case 4: statusMessage = (String)value$; break;
    case 5: createDate = (String)value$; break;
    case 6: insertTime = (String)value$; break;
    case 7: external = (Boolean)value$; break;
    case 8: accountAuthId = (String)value$; break;
    case 9: symbol = (String)value$; break;
    case 10: direction = (com.aqitrade.raduga.messagebus.messages.OrderStatusDirection)value$; break;
    case 11: price = (Double)value$; break;
    case 12: submittedQty = (Integer)value$; break;
    case 13: closeToday = (Boolean)value$; break;
    case 14: exchangeID = (String)value$; break;
    default: throw new org.apache.avro.AvroRuntimeException("Bad index");
    }
  }

  /**
   * Gets the value of the 'orderID' field.
   */
  public Long getOrderID() {
    return orderID;
  }

  /**
   * Sets the value of the 'orderID' field.
   * @param value the value to set.
   */
  public void setOrderID(Long value) {
    this.orderID = value;
  }

  /**
   * Gets the value of the 'exchangeOrderID' field.
   */
  public String getExchangeOrderID() {
    return exchangeOrderID;
  }

  /**
   * Sets the value of the 'exchangeOrderID' field.
   * @param value the value to set.
   */
  public void setExchangeOrderID(String value) {
    this.exchangeOrderID = value;
  }

  /**
   * Gets the value of the 'qty' field.
   */
  public Integer getQty() {
    return qty;
  }

  /**
   * Sets the value of the 'qty' field.
   * @param value the value to set.
   */
  public void setQty(Integer value) {
    this.qty = value;
  }

  /**
   * Gets the value of the 'status' field.
   */
  public OrderStatus getStatus() {
    return status;
  }

  /**
   * Sets the value of the 'status' field.
   * @param value the value to set.
   */
  public void setStatus(OrderStatus value) {
    this.status = value;
  }

  /**
   * Gets the value of the 'statusMessage' field.
   */
  public String getStatusMessage() {
    return statusMessage;
  }

  /**
   * Sets the value of the 'statusMessage' field.
   * @param value the value to set.
   */
  public void setStatusMessage(String value) {
    this.statusMessage = value;
  }

  /**
   * Gets the value of the 'createDate' field.
   */
  public String getCreateDate() {
    return createDate;
  }

  /**
   * Sets the value of the 'createDate' field.
   * @param value the value to set.
   */
  public void setCreateDate(String value) {
    this.createDate = value;
  }

  /**
   * Gets the value of the 'insertTime' field.
   */
  public String getInsertTime() {
    return insertTime;
  }

  /**
   * Sets the value of the 'insertTime' field.
   * @param value the value to set.
   */
  public void setInsertTime(String value) {
    this.insertTime = value;
  }

  /**
   * Gets the value of the 'external' field.
   */
  public Boolean getExternal() {
    return external;
  }

  /**
   * Sets the value of the 'external' field.
   * @param value the value to set.
   */
  public void setExternal(Boolean value) {
    this.external = value;
  }

  /**
   * Gets the value of the 'accountAuthId' field.
   */
  public String getAccountAuthId() {
    return accountAuthId;
  }

  /**
   * Sets the value of the 'accountAuthId' field.
   * @param value the value to set.
   */
  public void setAccountAuthId(String value) {
    this.accountAuthId = value;
  }

  /**
   * Gets the value of the 'symbol' field.
   */
  public String getSymbol() {
    return symbol;
  }

  /**
   * Sets the value of the 'symbol' field.
   * @param value the value to set.
   */
  public void setSymbol(String value) {
    this.symbol = value;
  }

  /**
   * Gets the value of the 'direction' field.
   */
  public com.aqitrade.raduga.messagebus.messages.OrderStatusDirection getDirection() {
    return direction;
  }

  /**
   * Sets the value of the 'direction' field.
   * @param value the value to set.
   */
  public void setDirection(com.aqitrade.raduga.messagebus.messages.OrderStatusDirection value) {
    this.direction = value;
  }

  /**
   * Gets the value of the 'price' field.
   */
  public Double getPrice() {
    return price;
  }

  /**
   * Sets the value of the 'price' field.
   * @param value the value to set.
   */
  public void setPrice(Double value) {
    this.price = value;
  }

  /**
   * Gets the value of the 'submittedQty' field.
   */
  public Integer getSubmittedQty() {
    return submittedQty;
  }

  /**
   * Sets the value of the 'submittedQty' field.
   * @param value the value to set.
   */
  public void setSubmittedQty(Integer value) {
    this.submittedQty = value;
  }

  /**
   * Gets the value of the 'closeToday' field.
   */
  public Boolean getCloseToday() {
    return closeToday;
  }

  /**
   * Sets the value of the 'closeToday' field.
   * @param value the value to set.
   */
  public void setCloseToday(Boolean value) {
    this.closeToday = value;
  }

  /**
   * Gets the value of the 'exchangeID' field.
   */
  public String getExchangeID() {
    return exchangeID;
  }

  /**
   * Sets the value of the 'exchangeID' field.
   * @param value the value to set.
   */
  public void setExchangeID(String value) {
    this.exchangeID = value;
  }

  /** Creates a new OrderStatusMessage RecordBuilder */
  public static Builder newBuilder() {
    return new Builder();
  }
  
  /** Creates a new OrderStatusMessage RecordBuilder by copying an existing Builder */
  public static Builder newBuilder(Builder other) {
    return new Builder(other);
  }
  
  /** Creates a new OrderStatusMessage RecordBuilder by copying an existing OrderStatusMessage instance */
  public static Builder newBuilder(OrderStatusMessage other) {
    return new Builder(other);
  }
  
  /**
   * RecordBuilder for OrderStatusMessage instances.
   */
  public static class Builder extends org.apache.avro.specific.SpecificRecordBuilderBase<OrderStatusMessage>
    implements org.apache.avro.data.RecordBuilder<OrderStatusMessage> {

    private long orderID;
    private String exchangeOrderID;
    private int qty;
    private OrderStatus status;
    private String statusMessage;
    private String createDate;
    private String insertTime;
    private boolean external;
    private String accountAuthId;
    private String symbol;
    private com.aqitrade.raduga.messagebus.messages.OrderStatusDirection direction;
    private double price;
    private int submittedQty;
    private boolean closeToday;
    private String exchangeID;

    /** Creates a new Builder */
    private Builder() {
      super(OrderStatusMessage.SCHEMA$);
    }
    
    /** Creates a Builder by copying an existing Builder */
    private Builder(Builder other) {
      super(other);
      if (isValidValue(fields()[0], other.orderID)) {
        this.orderID = data().deepCopy(fields()[0].schema(), other.orderID);
        fieldSetFlags()[0] = true;
      }
      if (isValidValue(fields()[1], other.exchangeOrderID)) {
        this.exchangeOrderID = data().deepCopy(fields()[1].schema(), other.exchangeOrderID);
        fieldSetFlags()[1] = true;
      }
      if (isValidValue(fields()[2], other.qty)) {
        this.qty = data().deepCopy(fields()[2].schema(), other.qty);
        fieldSetFlags()[2] = true;
      }
      if (isValidValue(fields()[3], other.status)) {
        this.status = data().deepCopy(fields()[3].schema(), other.status);
        fieldSetFlags()[3] = true;
      }
      if (isValidValue(fields()[4], other.statusMessage)) {
        this.statusMessage = data().deepCopy(fields()[4].schema(), other.statusMessage);
        fieldSetFlags()[4] = true;
      }
      if (isValidValue(fields()[5], other.createDate)) {
        this.createDate = data().deepCopy(fields()[5].schema(), other.createDate);
        fieldSetFlags()[5] = true;
      }
      if (isValidValue(fields()[6], other.insertTime)) {
        this.insertTime = data().deepCopy(fields()[6].schema(), other.insertTime);
        fieldSetFlags()[6] = true;
      }
      if (isValidValue(fields()[7], other.external)) {
        this.external = data().deepCopy(fields()[7].schema(), other.external);
        fieldSetFlags()[7] = true;
      }
      if (isValidValue(fields()[8], other.accountAuthId)) {
        this.accountAuthId = data().deepCopy(fields()[8].schema(), other.accountAuthId);
        fieldSetFlags()[8] = true;
      }
      if (isValidValue(fields()[9], other.symbol)) {
        this.symbol = data().deepCopy(fields()[9].schema(), other.symbol);
        fieldSetFlags()[9] = true;
      }
      if (isValidValue(fields()[10], other.direction)) {
        this.direction = data().deepCopy(fields()[10].schema(), other.direction);
        fieldSetFlags()[10] = true;
      }
      if (isValidValue(fields()[11], other.price)) {
        this.price = data().deepCopy(fields()[11].schema(), other.price);
        fieldSetFlags()[11] = true;
      }
      if (isValidValue(fields()[12], other.submittedQty)) {
        this.submittedQty = data().deepCopy(fields()[12].schema(), other.submittedQty);
        fieldSetFlags()[12] = true;
      }
      if (isValidValue(fields()[13], other.closeToday)) {
        this.closeToday = data().deepCopy(fields()[13].schema(), other.closeToday);
        fieldSetFlags()[13] = true;
      }
      if (isValidValue(fields()[14], other.exchangeID)) {
        this.exchangeID = data().deepCopy(fields()[14].schema(), other.exchangeID);
        fieldSetFlags()[14] = true;
      }
    }
    
    /** Creates a Builder by copying an existing OrderStatusMessage instance */
    private Builder(OrderStatusMessage other) {
            super(OrderStatusMessage.SCHEMA$);
      if (isValidValue(fields()[0], other.orderID)) {
        this.orderID = data().deepCopy(fields()[0].schema(), other.orderID);
        fieldSetFlags()[0] = true;
      }
      if (isValidValue(fields()[1], other.exchangeOrderID)) {
        this.exchangeOrderID = data().deepCopy(fields()[1].schema(), other.exchangeOrderID);
        fieldSetFlags()[1] = true;
      }
      if (isValidValue(fields()[2], other.qty)) {
        this.qty = data().deepCopy(fields()[2].schema(), other.qty);
        fieldSetFlags()[2] = true;
      }
      if (isValidValue(fields()[3], other.status)) {
        this.status = data().deepCopy(fields()[3].schema(), other.status);
        fieldSetFlags()[3] = true;
      }
      if (isValidValue(fields()[4], other.statusMessage)) {
        this.statusMessage = data().deepCopy(fields()[4].schema(), other.statusMessage);
        fieldSetFlags()[4] = true;
      }
      if (isValidValue(fields()[5], other.createDate)) {
        this.createDate = data().deepCopy(fields()[5].schema(), other.createDate);
        fieldSetFlags()[5] = true;
      }
      if (isValidValue(fields()[6], other.insertTime)) {
        this.insertTime = data().deepCopy(fields()[6].schema(), other.insertTime);
        fieldSetFlags()[6] = true;
      }
      if (isValidValue(fields()[7], other.external)) {
        this.external = data().deepCopy(fields()[7].schema(), other.external);
        fieldSetFlags()[7] = true;
      }
      if (isValidValue(fields()[8], other.accountAuthId)) {
        this.accountAuthId = data().deepCopy(fields()[8].schema(), other.accountAuthId);
        fieldSetFlags()[8] = true;
      }
      if (isValidValue(fields()[9], other.symbol)) {
        this.symbol = data().deepCopy(fields()[9].schema(), other.symbol);
        fieldSetFlags()[9] = true;
      }
      if (isValidValue(fields()[10], other.direction)) {
        this.direction = data().deepCopy(fields()[10].schema(), other.direction);
        fieldSetFlags()[10] = true;
      }
      if (isValidValue(fields()[11], other.price)) {
        this.price = data().deepCopy(fields()[11].schema(), other.price);
        fieldSetFlags()[11] = true;
      }
      if (isValidValue(fields()[12], other.submittedQty)) {
        this.submittedQty = data().deepCopy(fields()[12].schema(), other.submittedQty);
        fieldSetFlags()[12] = true;
      }
      if (isValidValue(fields()[13], other.closeToday)) {
        this.closeToday = data().deepCopy(fields()[13].schema(), other.closeToday);
        fieldSetFlags()[13] = true;
      }
      if (isValidValue(fields()[14], other.exchangeID)) {
        this.exchangeID = data().deepCopy(fields()[14].schema(), other.exchangeID);
        fieldSetFlags()[14] = true;
      }
    }

    /** Gets the value of the 'orderID' field */
    public Long getOrderID() {
      return orderID;
    }
    
    /** Sets the value of the 'orderID' field */
    public Builder setOrderID(long value) {
      validate(fields()[0], value);
      this.orderID = value;
      fieldSetFlags()[0] = true;
      return this; 
    }
    
    /** Checks whether the 'orderID' field has been set */
    public boolean hasOrderID() {
      return fieldSetFlags()[0];
    }
    
    /** Clears the value of the 'orderID' field */
    public Builder clearOrderID() {
      fieldSetFlags()[0] = false;
      return this;
    }

    /** Gets the value of the 'exchangeOrderID' field */
    public String getExchangeOrderID() {
      return exchangeOrderID;
    }
    
    /** Sets the value of the 'exchangeOrderID' field */
    public Builder setExchangeOrderID(String value) {
      validate(fields()[1], value);
      this.exchangeOrderID = value;
      fieldSetFlags()[1] = true;
      return this; 
    }
    
    /** Checks whether the 'exchangeOrderID' field has been set */
    public boolean hasExchangeOrderID() {
      return fieldSetFlags()[1];
    }
    
    /** Clears the value of the 'exchangeOrderID' field */
    public Builder clearExchangeOrderID() {
      exchangeOrderID = null;
      fieldSetFlags()[1] = false;
      return this;
    }

    /** Gets the value of the 'qty' field */
    public Integer getQty() {
      return qty;
    }
    
    /** Sets the value of the 'qty' field */
    public Builder setQty(int value) {
      validate(fields()[2], value);
      this.qty = value;
      fieldSetFlags()[2] = true;
      return this; 
    }
    
    /** Checks whether the 'qty' field has been set */
    public boolean hasQty() {
      return fieldSetFlags()[2];
    }
    
    /** Clears the value of the 'qty' field */
    public Builder clearQty() {
      fieldSetFlags()[2] = false;
      return this;
    }

    /** Gets the value of the 'status' field */
    public OrderStatus getStatus() {
      return status;
    }
    
    /** Sets the value of the 'status' field */
    public Builder setStatus(OrderStatus value) {
      validate(fields()[3], value);
      this.status = value;
      fieldSetFlags()[3] = true;
      return this; 
    }
    
    /** Checks whether the 'status' field has been set */
    public boolean hasStatus() {
      return fieldSetFlags()[3];
    }
    
    /** Clears the value of the 'status' field */
    public Builder clearStatus() {
      status = null;
      fieldSetFlags()[3] = false;
      return this;
    }

    /** Gets the value of the 'statusMessage' field */
    public String getStatusMessage() {
      return statusMessage;
    }
    
    /** Sets the value of the 'statusMessage' field */
    public Builder setStatusMessage(String value) {
      validate(fields()[4], value);
      this.statusMessage = value;
      fieldSetFlags()[4] = true;
      return this; 
    }
    
    /** Checks whether the 'statusMessage' field has been set */
    public boolean hasStatusMessage() {
      return fieldSetFlags()[4];
    }
    
    /** Clears the value of the 'statusMessage' field */
    public Builder clearStatusMessage() {
      statusMessage = null;
      fieldSetFlags()[4] = false;
      return this;
    }

    /** Gets the value of the 'createDate' field */
    public String getCreateDate() {
      return createDate;
    }
    
    /** Sets the value of the 'createDate' field */
    public Builder setCreateDate(String value) {
      validate(fields()[5], value);
      this.createDate = value;
      fieldSetFlags()[5] = true;
      return this; 
    }
    
    /** Checks whether the 'createDate' field has been set */
    public boolean hasCreateDate() {
      return fieldSetFlags()[5];
    }
    
    /** Clears the value of the 'createDate' field */
    public Builder clearCreateDate() {
      createDate = null;
      fieldSetFlags()[5] = false;
      return this;
    }

    /** Gets the value of the 'insertTime' field */
    public String getInsertTime() {
      return insertTime;
    }
    
    /** Sets the value of the 'insertTime' field */
    public Builder setInsertTime(String value) {
      validate(fields()[6], value);
      this.insertTime = value;
      fieldSetFlags()[6] = true;
      return this; 
    }
    
    /** Checks whether the 'insertTime' field has been set */
    public boolean hasInsertTime() {
      return fieldSetFlags()[6];
    }
    
    /** Clears the value of the 'insertTime' field */
    public Builder clearInsertTime() {
      insertTime = null;
      fieldSetFlags()[6] = false;
      return this;
    }

    /** Gets the value of the 'external' field */
    public Boolean getExternal() {
      return external;
    }
    
    /** Sets the value of the 'external' field */
    public Builder setExternal(boolean value) {
      validate(fields()[7], value);
      this.external = value;
      fieldSetFlags()[7] = true;
      return this; 
    }
    
    /** Checks whether the 'external' field has been set */
    public boolean hasExternal() {
      return fieldSetFlags()[7];
    }
    
    /** Clears the value of the 'external' field */
    public Builder clearExternal() {
      fieldSetFlags()[7] = false;
      return this;
    }

    /** Gets the value of the 'accountAuthId' field */
    public String getAccountAuthId() {
      return accountAuthId;
    }
    
    /** Sets the value of the 'accountAuthId' field */
    public Builder setAccountAuthId(String value) {
      validate(fields()[8], value);
      this.accountAuthId = value;
      fieldSetFlags()[8] = true;
      return this; 
    }
    
    /** Checks whether the 'accountAuthId' field has been set */
    public boolean hasAccountAuthId() {
      return fieldSetFlags()[8];
    }
    
    /** Clears the value of the 'accountAuthId' field */
    public Builder clearAccountAuthId() {
      accountAuthId = null;
      fieldSetFlags()[8] = false;
      return this;
    }

    /** Gets the value of the 'symbol' field */
    public String getSymbol() {
      return symbol;
    }
    
    /** Sets the value of the 'symbol' field */
    public Builder setSymbol(String value) {
      validate(fields()[9], value);
      this.symbol = value;
      fieldSetFlags()[9] = true;
      return this; 
    }
    
    /** Checks whether the 'symbol' field has been set */
    public boolean hasSymbol() {
      return fieldSetFlags()[9];
    }
    
    /** Clears the value of the 'symbol' field */
    public Builder clearSymbol() {
      symbol = null;
      fieldSetFlags()[9] = false;
      return this;
    }

    /** Gets the value of the 'direction' field */
    public com.aqitrade.raduga.messagebus.messages.OrderStatusDirection getDirection() {
      return direction;
    }
    
    /** Sets the value of the 'direction' field */
    public Builder setDirection(com.aqitrade.raduga.messagebus.messages.OrderStatusDirection value) {
      validate(fields()[10], value);
      this.direction = value;
      fieldSetFlags()[10] = true;
      return this; 
    }
    
    /** Checks whether the 'direction' field has been set */
    public boolean hasDirection() {
      return fieldSetFlags()[10];
    }
    
    /** Clears the value of the 'direction' field */
    public Builder clearDirection() {
      direction = null;
      fieldSetFlags()[10] = false;
      return this;
    }

    /** Gets the value of the 'price' field */
    public Double getPrice() {
      return price;
    }
    
    /** Sets the value of the 'price' field */
    public Builder setPrice(double value) {
      validate(fields()[11], value);
      this.price = value;
      fieldSetFlags()[11] = true;
      return this; 
    }
    
    /** Checks whether the 'price' field has been set */
    public boolean hasPrice() {
      return fieldSetFlags()[11];
    }
    
    /** Clears the value of the 'price' field */
    public Builder clearPrice() {
      fieldSetFlags()[11] = false;
      return this;
    }

    /** Gets the value of the 'submittedQty' field */
    public Integer getSubmittedQty() {
      return submittedQty;
    }
    
    /** Sets the value of the 'submittedQty' field */
    public Builder setSubmittedQty(int value) {
      validate(fields()[12], value);
      this.submittedQty = value;
      fieldSetFlags()[12] = true;
      return this; 
    }
    
    /** Checks whether the 'submittedQty' field has been set */
    public boolean hasSubmittedQty() {
      return fieldSetFlags()[12];
    }
    
    /** Clears the value of the 'submittedQty' field */
    public Builder clearSubmittedQty() {
      fieldSetFlags()[12] = false;
      return this;
    }

    /** Gets the value of the 'closeToday' field */
    public Boolean getCloseToday() {
      return closeToday;
    }
    
    /** Sets the value of the 'closeToday' field */
    public Builder setCloseToday(boolean value) {
      validate(fields()[13], value);
      this.closeToday = value;
      fieldSetFlags()[13] = true;
      return this; 
    }
    
    /** Checks whether the 'closeToday' field has been set */
    public boolean hasCloseToday() {
      return fieldSetFlags()[13];
    }
    
    /** Clears the value of the 'closeToday' field */
    public Builder clearCloseToday() {
      fieldSetFlags()[13] = false;
      return this;
    }

    /** Gets the value of the 'exchangeID' field */
    public String getExchangeID() {
      return exchangeID;
    }
    
    /** Sets the value of the 'exchangeID' field */
    public Builder setExchangeID(String value) {
      validate(fields()[14], value);
      this.exchangeID = value;
      fieldSetFlags()[14] = true;
      return this; 
    }
    
    /** Checks whether the 'exchangeID' field has been set */
    public boolean hasExchangeID() {
      return fieldSetFlags()[14];
    }
    
    /** Clears the value of the 'exchangeID' field */
    public Builder clearExchangeID() {
      exchangeID = null;
      fieldSetFlags()[14] = false;
      return this;
    }

    @Override
    public OrderStatusMessage build() {
      try {
        OrderStatusMessage record = new OrderStatusMessage();
        record.orderID = fieldSetFlags()[0] ? this.orderID : (Long) defaultValue(fields()[0]);
        record.exchangeOrderID = fieldSetFlags()[1] ? this.exchangeOrderID : (String) defaultValue(fields()[1]);
        record.qty = fieldSetFlags()[2] ? this.qty : (Integer) defaultValue(fields()[2]);
        record.status = fieldSetFlags()[3] ? this.status : (OrderStatus) defaultValue(fields()[3]);
        record.statusMessage = fieldSetFlags()[4] ? this.statusMessage : (String) defaultValue(fields()[4]);
        record.createDate = fieldSetFlags()[5] ? this.createDate : (String) defaultValue(fields()[5]);
        record.insertTime = fieldSetFlags()[6] ? this.insertTime : (String) defaultValue(fields()[6]);
        record.external = fieldSetFlags()[7] ? this.external : (Boolean) defaultValue(fields()[7]);
        record.accountAuthId = fieldSetFlags()[8] ? this.accountAuthId : (String) defaultValue(fields()[8]);
        record.symbol = fieldSetFlags()[9] ? this.symbol : (String) defaultValue(fields()[9]);
        record.direction = fieldSetFlags()[10] ? this.direction : (com.aqitrade.raduga.messagebus.messages.OrderStatusDirection) defaultValue(fields()[10]);
        record.price = fieldSetFlags()[11] ? this.price : (Double) defaultValue(fields()[11]);
        record.submittedQty = fieldSetFlags()[12] ? this.submittedQty : (Integer) defaultValue(fields()[12]);
        record.closeToday = fieldSetFlags()[13] ? this.closeToday : (Boolean) defaultValue(fields()[13]);
        record.exchangeID = fieldSetFlags()[14] ? this.exchangeID : (String) defaultValue(fields()[14]);
        return record;
      } catch (Exception e) {
        throw new org.apache.avro.AvroRuntimeException(e);
      }
    }
  }
}
