/**
 * Autogenerated by Avro
 * 
 * DO NOT EDIT DIRECTLY
 */
package com.aqitrade.raduga.messagebus.messages;  
@SuppressWarnings("all")
@org.apache.avro.specific.AvroGenerated
public class UnsubscribeMarketDataMessage extends org.apache.avro.specific.SpecificRecordBase implements org.apache.avro.specific.SpecificRecord {
  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"record\",\"name\":\"UnsubscribeMarketDataMessage\",\"namespace\":\"com.aqitrade.raduga.messagebus.messages\",\"fields\":[{\"name\":\"exchangeID\",\"type\":{\"type\":\"string\",\"avro.java.string\":\"String\"}},{\"name\":\"symbolList\",\"type\":{\"type\":\"array\",\"items\":{\"type\":\"string\",\"avro.java.string\":\"String\"}}},{\"name\":\"createDate\",\"type\":{\"type\":\"string\",\"avro.java.string\":\"String\"}}]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }
  @Deprecated public String exchangeID;
  @Deprecated public java.util.List<String> symbolList;
  @Deprecated public String createDate;

  /**
   * Default constructor.  Note that this does not initialize fields
   * to their default values from the schema.  If that is desired then
   * one should use {@link \#newBuilder()}. 
   */
  public UnsubscribeMarketDataMessage() {}

  /**
   * All-args constructor.
   */
  public UnsubscribeMarketDataMessage(String exchangeID, java.util.List<String> symbolList, String createDate) {
    this.exchangeID = exchangeID;
    this.symbolList = symbolList;
    this.createDate = createDate;
  }

  public org.apache.avro.Schema getSchema() { return SCHEMA$; }
  // Used by DatumWriter.  Applications should not call. 
  public Object get(int field$) {
    switch (field$) {
    case 0: return exchangeID;
    case 1: return symbolList;
    case 2: return createDate;
    default: throw new org.apache.avro.AvroRuntimeException("Bad index");
    }
  }
  // Used by DatumReader.  Applications should not call. 
  @SuppressWarnings(value="unchecked")
  public void put(int field$, Object value$) {
    switch (field$) {
    case 0: exchangeID = (String)value$; break;
    case 1: symbolList = (java.util.List<String>)value$; break;
    case 2: createDate = (String)value$; break;
    default: throw new org.apache.avro.AvroRuntimeException("Bad index");
    }
  }

  /**
   * Gets the value of the 'exchangeID' field.
   */
  public String getExchangeID() {
    return exchangeID;
  }

  /**
   * Sets the value of the 'exchangeID' field.
   * @param value the value to set.
   */
  public void setExchangeID(String value) {
    this.exchangeID = value;
  }

  /**
   * Gets the value of the 'symbolList' field.
   */
  public java.util.List<String> getSymbolList() {
    return symbolList;
  }

  /**
   * Sets the value of the 'symbolList' field.
   * @param value the value to set.
   */
  public void setSymbolList(java.util.List<String> value) {
    this.symbolList = value;
  }

  /**
   * Gets the value of the 'createDate' field.
   */
  public String getCreateDate() {
    return createDate;
  }

  /**
   * Sets the value of the 'createDate' field.
   * @param value the value to set.
   */
  public void setCreateDate(String value) {
    this.createDate = value;
  }

  /** Creates a new UnsubscribeMarketDataMessage RecordBuilder */
  public static Builder newBuilder() {
    return new Builder();
  }
  
  /** Creates a new UnsubscribeMarketDataMessage RecordBuilder by copying an existing Builder */
  public static Builder newBuilder(Builder other) {
    return new Builder(other);
  }
  
  /** Creates a new UnsubscribeMarketDataMessage RecordBuilder by copying an existing UnsubscribeMarketDataMessage instance */
  public static Builder newBuilder(UnsubscribeMarketDataMessage other) {
    return new Builder(other);
  }
  
  /**
   * RecordBuilder for UnsubscribeMarketDataMessage instances.
   */
  public static class Builder extends org.apache.avro.specific.SpecificRecordBuilderBase<UnsubscribeMarketDataMessage>
    implements org.apache.avro.data.RecordBuilder<UnsubscribeMarketDataMessage> {

    private String exchangeID;
    private java.util.List<String> symbolList;
    private String createDate;

    /** Creates a new Builder */
    private Builder() {
      super(UnsubscribeMarketDataMessage.SCHEMA$);
    }
    
    /** Creates a Builder by copying an existing Builder */
    private Builder(Builder other) {
      super(other);
      if (isValidValue(fields()[0], other.exchangeID)) {
        this.exchangeID = data().deepCopy(fields()[0].schema(), other.exchangeID);
        fieldSetFlags()[0] = true;
      }
      if (isValidValue(fields()[1], other.symbolList)) {
        this.symbolList = data().deepCopy(fields()[1].schema(), other.symbolList);
        fieldSetFlags()[1] = true;
      }
      if (isValidValue(fields()[2], other.createDate)) {
        this.createDate = data().deepCopy(fields()[2].schema(), other.createDate);
        fieldSetFlags()[2] = true;
      }
    }
    
    /** Creates a Builder by copying an existing UnsubscribeMarketDataMessage instance */
    private Builder(UnsubscribeMarketDataMessage other) {
            super(UnsubscribeMarketDataMessage.SCHEMA$);
      if (isValidValue(fields()[0], other.exchangeID)) {
        this.exchangeID = data().deepCopy(fields()[0].schema(), other.exchangeID);
        fieldSetFlags()[0] = true;
      }
      if (isValidValue(fields()[1], other.symbolList)) {
        this.symbolList = data().deepCopy(fields()[1].schema(), other.symbolList);
        fieldSetFlags()[1] = true;
      }
      if (isValidValue(fields()[2], other.createDate)) {
        this.createDate = data().deepCopy(fields()[2].schema(), other.createDate);
        fieldSetFlags()[2] = true;
      }
    }

    /** Gets the value of the 'exchangeID' field */
    public String getExchangeID() {
      return exchangeID;
    }
    
    /** Sets the value of the 'exchangeID' field */
    public Builder setExchangeID(String value) {
      validate(fields()[0], value);
      this.exchangeID = value;
      fieldSetFlags()[0] = true;
      return this; 
    }
    
    /** Checks whether the 'exchangeID' field has been set */
    public boolean hasExchangeID() {
      return fieldSetFlags()[0];
    }
    
    /** Clears the value of the 'exchangeID' field */
    public Builder clearExchangeID() {
      exchangeID = null;
      fieldSetFlags()[0] = false;
      return this;
    }

    /** Gets the value of the 'symbolList' field */
    public java.util.List<String> getSymbolList() {
      return symbolList;
    }
    
    /** Sets the value of the 'symbolList' field */
    public Builder setSymbolList(java.util.List<String> value) {
      validate(fields()[1], value);
      this.symbolList = value;
      fieldSetFlags()[1] = true;
      return this; 
    }
    
    /** Checks whether the 'symbolList' field has been set */
    public boolean hasSymbolList() {
      return fieldSetFlags()[1];
    }
    
    /** Clears the value of the 'symbolList' field */
    public Builder clearSymbolList() {
      symbolList = null;
      fieldSetFlags()[1] = false;
      return this;
    }

    /** Gets the value of the 'createDate' field */
    public String getCreateDate() {
      return createDate;
    }
    
    /** Sets the value of the 'createDate' field */
    public Builder setCreateDate(String value) {
      validate(fields()[2], value);
      this.createDate = value;
      fieldSetFlags()[2] = true;
      return this; 
    }
    
    /** Checks whether the 'createDate' field has been set */
    public boolean hasCreateDate() {
      return fieldSetFlags()[2];
    }
    
    /** Clears the value of the 'createDate' field */
    public Builder clearCreateDate() {
      createDate = null;
      fieldSetFlags()[2] = false;
      return this;
    }

    @Override
    public UnsubscribeMarketDataMessage build() {
      try {
        UnsubscribeMarketDataMessage record = new UnsubscribeMarketDataMessage();
        record.exchangeID = fieldSetFlags()[0] ? this.exchangeID : (String) defaultValue(fields()[0]);
        record.symbolList = fieldSetFlags()[1] ? this.symbolList : (java.util.List<String>) defaultValue(fields()[1]);
        record.createDate = fieldSetFlags()[2] ? this.createDate : (String) defaultValue(fields()[2]);
        return record;
      } catch (Exception e) {
        throw new org.apache.avro.AvroRuntimeException(e);
      }
    }
  }
}
